sonar.projectKey=Realtime-Monitoring-Platform_Frontend
sonar.organization=realtime-monitoring-platform
sonar.projectName=Realtime-Monitoring-Frontend

sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.exclusions=node_modules/**,dist/**,coverage/**,.scannerwork/**,src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx

sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx,src/**/*.spec.ts,src/**/*.spec.tsx

sonar.coverage.exclusions=src/components/ui/**,src/assets/**,src/types/**,src/styles/**,src/main.tsx,src/App.tsx,src/vite-env.d.ts,src/services/api.ts

sonar.duplications.exclusions=src/components/ui/**,src/assets/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info