import { useQuery } from '@tanstack/react-query';
import { ColumnDef } from '@tanstack/react-table';
import { Download, FileText, FileSpreadsheet } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Spinner } from '@/components/ui/spinner';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { DataTable } from '@/components/data-table';
import { api } from '../../../services/api';
import { mockReports } from '@/services/mockData';

type Report = {
  id: string;
  name: string;
  type: string;
  format: string;
  generatedBy: string;
  generatedAt: string;
  downloadUrl: string;
};

export const ReportsPage = () => {
  

  const getFormatIcon = (format: string) => {
    switch (format) {
      case 'PDF': return <FileText className="h-4 w-4" />;
      case 'EXCEL': return <FileSpreadsheet className="h-4 w-4" />;
      default: return <Download className="h-4 w-4" />;
    }
  };

  const columns: ColumnDef<Report>[] = [
    { accessorKey: 'name', header: 'Report Name' },
    { accessorKey: 'type', header: 'Type' },
    {
      accessorKey: 'format',
      header: 'Format',
      cell: ({ getValue }) => {
        const value = getValue() as string;
        return (
          <div className="flex items-center gap-2">
            {getFormatIcon(value)}
            <span>{value}</span>
          </div>
        );
      },
    },
    { accessorKey: 'generatedBy', header: 'Generated By' },
    {
      accessorKey: 'generatedAt',
      header: 'Generated At',
      cell: ({ getValue }) => {
        const value = getValue() as string;
        return new Date(value).toLocaleString();
      },
    },
    {
      id: 'actions',
      header: 'Actions',
      cell: ({ row }) => (
        <Button
          size="sm"
          variant="ghost"
          onClick={() => window.open(row.original.downloadUrl, '_blank')}
        >
          <Download className="h-4 w-4" />
        </Button>
      ),
    },
  ];

  // if (isLoading) {
  //   return (
  //     <div className="flex h-96 w-full items-center justify-center">
  //       <Spinner className="h-8 w-8" />
  //     </div>
  //   );
  // }

  // if (error) {
  //   return <Alert variant="destructive"><AlertDescription>Failed to load reports</AlertDescription></Alert>;
  // }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Reports</h1>
          <p className="text-sm text-muted-foreground">Generate and download reports</p>
        </div>
        <div className="flex gap-2">
          <Button variant="outline">
            <FileText className="mr-2 h-4 w-4" />
            Export PDF
          </Button>
          <Button>
            <FileSpreadsheet className="mr-2 h-4 w-4" />
            Export Excel
          </Button>
        </div>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Reports</CardTitle>
        </CardHeader>
        <CardContent>
          <DataTable
            columns={columns}
            data={mockReports || []}
            searchKey="name"
            searchPlaceholder="Search reports..."
          />
        </CardContent>
      </Card>
    </div>
  );
};
